// The starter recipe pack offered to an account whose recipe book is still
// empty (see StarterRecipesModal). Everyday, low-effort dishes: the point is
// that a new user can plan a week without typing a recipe first. The pack
// covers all three courses, so a fresh account can generate a plan with side
// dishes as well as mains.
//
// Two rules the tests enforce, both about not damaging the seeded account:
//
// * every `name` must already exist in backend/data/system_ingredients.json,
//   so importing reuses the account's own ingredient rows (with their real
//   seasonality and units) instead of inventing all-year ones;
// * every tag must be one of the system tags seeded by
//   backend/mealplanner/seed.py -- the pack introduces no tag vocabulary.
//
// Quantities are written for one person unless the entry says otherwise with
// `servings` -- the head-count models.Recipe stores and the shopping list
// divides by. A recipe that would otherwise ask for a fraction of a countable
// thing (half an egg) states a larger basis instead. `minutes` is shown in the modal to help the user
// choose and is deliberately not persisted: Recipe has no time column.

export const STARTER_RECIPES = [
  // --- first courses -------------------------------------------------
  {
    slug: 'fresh-tomato-sauce-pasta',
    title: 'Pasta with Fresh Tomato Sauce',
    minutes: 20,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegan', 'quick', 'cheap'],
    blurb: 'Ten minutes of tomatoes in a pan, no simmering afternoon needed.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Tomato', quantity: 250, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Sugar', quantity: 3, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Cook the tomatoes in the oil over high heat until they collapse.',
      'Add the garlic, salt and a pinch of sugar once they soften.',
      'Finish with basil or rosemary and toss the drained pasta through.',
    ].join('\n'),
  },
  {
    slug: 'aglio-olio-peperoncino',
    title: 'Spaghetti Aglio, Olio e Peperoncino',
    minutes: 15,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegan', 'quick', 'cheap', 'spicy'],
    blurb: 'Three ingredients, and still the best late dinner there is.',
    ingredients: [
      { name: 'Spaghetti', quantity: 90, unit: 'g' },
      { name: 'Garlic', quantity: 8, unit: 'g' },
      { name: 'Chili Pepper', quantity: 2, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Parsley', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Warm the sliced garlic and chili gently in the oil; do not brown them.',
      'Drain the spaghetti a minute early and finish it in the pan with its water.',
      'Toss hard so the oil and water emulsify, then add the parsley.',
    ].join('\n'),
  },
  {
    slug: 'pasta-alla-norma',
    title: 'Pasta alla Norma',
    minutes: 35,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegetarian'],
    blurb: 'Pan-fried eggplant, simple tomato sauce, ricotta salata.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Eggplant', quantity: 150, unit: 'g' },
      { name: 'Passata', quantity: 150, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
      { name: 'Ricotta Salata', quantity: 20, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Fry the eggplant cubes until deep gold and drain them.',
      'Simmer the passata with the garlic for 10 minutes.',
      'Toss the pasta through the sauce, fold in the eggplant, grate over the ricotta salata.',
    ].join('\n'),
  },
  {
    slug: 'spaghetti-carbonara',
    title: 'Spaghetti Carbonara',
    minutes: 25,
    course: 'first-course',
    // Written for two: carbonara for one needs half an egg, which nobody does.
    servings: 2,
    bulk_prep: false,
    tags: ['pasta', 'meat', 'quick'],
    blurb: 'Eggs, cheese, pepper and pasta water -- no cream anywhere.',
    ingredients: [
      { name: 'Spaghetti', quantity: 180, unit: 'g' },
      { name: 'Bacon', quantity: 120, unit: 'g' },
      { name: 'Egg', quantity: 3, unit: 'piece' },
      { name: 'Parmesan', quantity: 60, unit: 'g' },
      { name: 'Black Pepper', quantity: 4, unit: 'g' },
    ],
    procedure: [
      'Render the bacon slowly until crisp and keep the fat.',
      'Beat the eggs with the parmesan and plenty of black pepper.',
      'Off the heat, toss the drained pasta with the bacon, then the eggs, loosening with pasta water.',
    ].join('\n'),
  },
  {
    slug: 'pasta-al-ragu',
    title: 'Pasta al Ragu',
    minutes: 120,
    course: 'first-course',
    bulk_prep: true,
    tags: ['pasta', 'meat'],
    blurb: 'A long Sunday simmer that reheats better than it started.',
    ingredients: [
      { name: 'Pasta', quantity: 90, unit: 'g' },
      { name: 'Ground Beef', quantity: 100, unit: 'g' },
      { name: 'Passata', quantity: 200, unit: 'g' },
      { name: 'Carrot', quantity: 40, unit: 'g' },
      { name: 'Celery', quantity: 30, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Red Wine', quantity: 30, unit: 'ml' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Soften the diced carrot, celery and onion in the oil.',
      'Brown the mince hard, then deglaze with the wine.',
      'Add the passata and simmer at least 90 minutes, topping up with water.',
      'Dress the pasta in the pan with a ladle of its cooking water.',
    ].join('\n'),
  },
  {
    slug: 'tuna-cherry-tomato-pasta',
    title: 'Tuna and Cherry Tomato Pasta',
    minutes: 20,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'quick', 'cheap'],
    blurb: 'Pure storecupboard -- always makeable.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Canned Tuna', quantity: 80, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 120, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Parsley', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Burst the cherry tomatoes in oil with the garlic over high heat.',
      'Add the drained tuna and break it up; season.',
      'Toss the drained pasta through with a splash of its water and the parsley.',
    ].join('\n'),
  },
  {
    slug: 'smoked-tofu-eggplant-pasta',
    title: 'Pasta with Smoked Tofu and Eggplant',
    minutes: 30,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegan'],
    blurb: 'The smoked tofu does what pancetta does, without the pancetta.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Smoked Tofu', quantity: 80, unit: 'g' },
      { name: 'Eggplant', quantity: 150, unit: 'g' },
      { name: 'Passata', quantity: 150, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Basil', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Sear the diced smoked tofu until the edges crisp, then set it aside.',
      'Brown the eggplant in the same pan, adding oil as it drinks it.',
      'Pour in the passata with the garlic and simmer 10 minutes.',
      'Return the tofu, then toss the pasta through with basil.',
    ].join('\n'),
  },
  {
    slug: 'pasta-chickpea-cream-confit-tomatoes',
    title: 'Pasta with Chickpea Cream and Confit Tomatoes',
    minutes: 35,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegan'],
    blurb: 'Blended chickpeas for the cream, slow tomatoes for the sweetness.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Chickpeas', quantity: 120, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 120, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
      { name: 'Lemon', quantity: 10, unit: 'g' },
    ],
    procedure: [
      'Confit the cherry tomatoes with oil, garlic and thyme in a low oven or air fryer, 25 minutes.',
      'Blend the chickpeas with a little cooking water and oil into a loose cream.',
      'Warm the cream in the pan, toss the pasta through it, top with the tomatoes.',
      'Grate over lemon zest -- it lifts the whole plate.',
    ].join('\n'),
  },
  {
    slug: 'cauliflower-miso-pasta',
    title: 'Pasta with Cauliflower Miso Cream',
    minutes: 35,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegan'],
    blurb: 'Roasted cauliflower blended with miso, walnuts and seared smoked tofu.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Cauliflower', quantity: 180, unit: 'g' },
      { name: 'Miso Paste', quantity: 15, unit: 'g' },
      { name: 'Walnuts', quantity: 20, unit: 'g' },
      { name: 'Smoked Tofu', quantity: 70, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Roast or boil the cauliflower until fully soft.',
      'Blend it with the miso, garlic and a little pasta water into a cream.',
      'Sear the diced smoked tofu separately until crisp.',
      'Toss the pasta through the cream; finish with the tofu and toasted walnuts.',
    ].join('\n'),
  },
  {
    slug: 'baked-pasta-zucchini-pesto',
    title: 'Baked Pasta with Zucchini Pesto',
    minutes: 60,
    course: 'first-course',
    bulk_prep: true,
    tags: ['pasta', 'vegetarian'],
    blurb: 'A light bechamel and a pan of green vegetables, baked until the top catches.',
    ingredients: [
      { name: 'Pasta', quantity: 90, unit: 'g' },
      { name: 'Zucchini', quantity: 150, unit: 'g' },
      { name: 'Peas', quantity: 60, unit: 'g' },
      { name: 'Green Beans', quantity: 60, unit: 'g' },
      { name: 'Milk', quantity: 150, unit: 'ml' },
      { name: 'Flour', quantity: 12, unit: 'g' },
      { name: 'Butter', quantity: 10, unit: 'g' },
      { name: 'Pine Nuts', quantity: 10, unit: 'g' },
      { name: 'Parmesan', quantity: 20, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
    ],
    procedure: [
      'Make a light bechamel with the butter, flour and milk.',
      'Blend half the zucchini with the pine nuts and parmesan into a pesto.',
      'Saute the rest of the zucchini, the peas and the green beans with garlic.',
      'Fold everything through half-cooked pasta and bake 20 minutes at 200 C.',
    ].join('\n'),
  },
  {
    slug: 'bulgur-zucchini-peas',
    title: 'Bulgur with Zucchini, Peas and Lemon',
    minutes: 25,
    course: 'first-course',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Works the same with couscous or quinoa -- whatever is in the cupboard.',
    ingredients: [
      { name: 'Bulgur', quantity: 80, unit: 'g' },
      { name: 'Zucchini', quantity: 150, unit: 'g' },
      { name: 'Peas', quantity: 70, unit: 'g' },
      { name: 'Lemon', quantity: 15, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Mint', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Cook the bulgur in salted water or stock and let it stand covered.',
      'Saute the diced zucchini hard, adding the peas at the end.',
      'Fold everything together off the heat with lemon zest, juice and mint.',
    ].join('\n'),
  },
  {
    slug: 'pasta-alla-genovese-seitan',
    title: 'Pasta alla Genovese with Seitan',
    minutes: 90,
    course: 'first-course',
    bulk_prep: true,
    tags: ['pasta', 'vegan'],
    blurb: 'Onions cooked down for an hour until they are the sauce.',
    ingredients: [
      { name: 'Pasta', quantity: 90, unit: 'g' },
      { name: 'Seitan', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 300, unit: 'g' },
      { name: 'Carrot', quantity: 40, unit: 'g' },
      { name: 'Celery', quantity: 30, unit: 'g' },
      { name: 'White Wine', quantity: 30, unit: 'ml' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Brown the seitan pieces, then set them aside.',
      'Add the sliced onions with the carrot and celery and a splash of water.',
      'Cook covered for an hour, stirring, until the onions melt; deglaze with the wine.',
      'Return the seitan, cook 15 minutes more, then dress the pasta with it.',
    ].join('\n'),
  },
  {
    slug: 'mushroom-risotto',
    title: 'Mushroom Risotto',
    minutes: 40,
    course: 'first-course',
    bulk_prep: false,
    tags: ['risotto', 'vegetarian'],
    blurb: 'One pan, one ladle, twenty minutes of stirring.',
    ingredients: [
      { name: 'Arborio Rice', quantity: 80, unit: 'g' },
      { name: 'Mushroom', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 40, unit: 'g' },
      { name: 'White Wine', quantity: 30, unit: 'ml' },
      { name: 'Vegetable Stock', quantity: 400, unit: 'ml' },
      { name: 'Butter', quantity: 15, unit: 'g' },
      { name: 'Parmesan', quantity: 25, unit: 'g' },
    ],
    procedure: [
      'Sear the mushrooms hard in a dry pan first, then set them aside.',
      'Soften the onion, toast the rice, deglaze with the wine.',
      'Add hot stock a ladle at a time for about 18 minutes.',
      'Off the heat, beat in the butter and parmesan and fold the mushrooms back in.',
    ].join('\n'),
  },
  {
    slug: 'minestrone',
    title: 'Minestrone',
    minutes: 50,
    course: 'first-course',
    bulk_prep: true,
    tags: ['soup', 'vegan', 'cheap'],
    blurb: 'Whatever the fridge holds, plus beans and a small pasta.',
    ingredients: [
      { name: 'Carrot', quantity: 60, unit: 'g' },
      { name: 'Celery', quantity: 40, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Potato', quantity: 80, unit: 'g' },
      { name: 'Zucchini', quantity: 80, unit: 'g' },
      { name: 'Cannellini Beans', quantity: 80, unit: 'g' },
      { name: 'Pasta', quantity: 40, unit: 'g' },
      { name: 'Canned Tomatoes', quantity: 80, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Sweat the diced carrot, celery and onion in the oil.',
      'Add the rest of the vegetables and the tomatoes, cover with water, simmer 30 minutes.',
      'Blend a ladleful and stir it back in for body.',
      'Cook the pasta in the pot and add the beans for the last five minutes.',
    ].join('\n'),
  },
  // --- mains ---------------------------------------------------------
  {
    slug: 'chickpea-hummus-tart',
    title: 'Chickpea Hummus Tart with Caramelised Onion',
    minutes: 60,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'A hummus base under sweet onions and peppers -- sugar only, no vinegar.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Chickpeas', quantity: 120, unit: 'g' },
      { name: 'Carrot', quantity: 60, unit: 'g' },
      { name: 'Walnuts', quantity: 15, unit: 'g' },
      { name: 'Almonds', quantity: 15, unit: 'g' },
      { name: 'Onion', quantity: 80, unit: 'g' },
      { name: 'Bell Pepper', quantity: 80, unit: 'g' },
      { name: 'Sugar', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Boil the carrots, then blend them with the chickpeas, walnuts and almonds.',
      'Caramelise the sliced onion and pepper slowly with the sugar; no vinegar.',
      'Spread the hummus over the pastry, top with the onions and peppers.',
      'Bake 30 minutes at 190 C, until the base is cooked through.',
    ].join('\n'),
  },
  {
    slug: 'cannellini-tomato-tart',
    title: 'Cannellini and Cherry Tomato Tart',
    minutes: 55,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'White bean cream, halved tomatoes, thyme and oregano.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Cannellini Beans', quantity: 130, unit: 'g' },
      { name: 'Onion', quantity: 70, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 120, unit: 'g' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
      { name: 'Oregano', quantity: 2, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Blend the cannellini with oil, salt and a splash of water into a thick cream.',
      'Soften the sliced onion in a pan until sweet.',
      'Spread the cream on the pastry, scatter over the onion and halved tomatoes.',
      'Bake 30 minutes at 190 C and finish with thyme and oregano.',
    ].join('\n'),
  },
  {
    slug: 'pea-leek-tart',
    title: 'Pea and Leek Tart with Lemon Zest',
    minutes: 55,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'The lemon zest goes on cold, at the end, so it stays sharp.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Peas', quantity: 140, unit: 'g' },
      { name: 'Leek', quantity: 100, unit: 'g' },
      { name: 'Lemon', quantity: 15, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Mint', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Sweat the sliced leek until soft and sweet.',
      'Blend most of the peas into a cream, keeping some whole for texture.',
      'Spread over the pastry, top with the leek, bake 30 minutes at 190 C.',
      'Grate the lemon zest over once the tart is out of the oven.',
    ].join('\n'),
  },
  {
    slug: 'pesto-green-bean-potato-tart',
    title: 'Pesto, Green Bean and Potato Tart',
    minutes: 60,
    course: 'main',
    bulk_prep: true,
    tags: ['vegetarian'],
    blurb: 'The Ligurian pasta plate, rebuilt on pastry.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Pesto', quantity: 30, unit: 'g' },
      { name: 'Green Beans', quantity: 100, unit: 'g' },
      { name: 'Potato', quantity: 150, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Boil the potatoes and beans until just tender, then drain them well.',
      'Spread the pesto over the pastry.',
      'Lay the sliced potato and the beans on top and season.',
      'Bake 30 minutes at 190 C.',
    ].join('\n'),
  },
  {
    slug: 'lentil-radicchio-tart',
    title: 'Lentil and Radicchio Tart with Walnuts',
    minutes: 60,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'Sweet-sour radicchio against a savoury lentil base.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Lentils', quantity: 120, unit: 'g' },
      { name: 'Soy Sauce', quantity: 10, unit: 'ml' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Walnuts', quantity: 20, unit: 'g' },
      { name: 'Radicchio', quantity: 100, unit: 'g' },
      { name: 'Balsamic Vinegar', quantity: 10, unit: 'ml' },
      { name: 'Sugar', quantity: 5, unit: 'g' },
    ],
    procedure: [
      'Blend the cooked lentils with the soy sauce, rosemary and walnuts.',
      'Fry the radicchio hard with the vinegar, sugar and salt until it collapses.',
      'Spread the lentil cream on the pastry and top with the radicchio.',
      'Bake 30 minutes at 190 C. Caramelised onions on top work well too.',
    ].join('\n'),
  },
  {
    slug: 'chickpea-leek-tart',
    title: 'Chickpea and Caramelised Leek Tart',
    minutes: 55,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'Two ingredients doing all the work.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Chickpeas', quantity: 130, unit: 'g' },
      { name: 'Leek', quantity: 120, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Blend the chickpeas into a thick cream with oil and salt.',
      'Cook the sliced leek low and slow until it caramelises.',
      'Assemble on the pastry and bake 30 minutes at 190 C.',
    ].join('\n'),
  },
  {
    slug: 'potato-chard-olive-tart',
    title: 'Potato, Chard and Olive Tart',
    minutes: 60,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Chard or spinach, whichever the market had.',
    ingredients: [
      { name: 'Puff Pastry', quantity: 90, unit: 'g' },
      { name: 'Potato', quantity: 150, unit: 'g' },
      { name: 'Swiss Chard', quantity: 120, unit: 'g' },
      { name: 'Olives', quantity: 30, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Boil the sliced potatoes until just tender.',
      'Wilt the chard with garlic and squeeze it dry.',
      'Layer both over the pastry with the olives and bake 30 minutes at 190 C.',
    ].join('\n'),
  },
  {
    slug: 'potato-leek-kale-soup',
    title: 'Potato, Leek and Kale Soup',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['soup', 'vegan', 'cheap'],
    blurb: 'Blended chickpeas turn a thin soup into dinner.',
    ingredients: [
      { name: 'Potato', quantity: 200, unit: 'g' },
      { name: 'Leek', quantity: 100, unit: 'g' },
      { name: 'Chickpeas', quantity: 100, unit: 'g' },
      { name: 'Kale', quantity: 80, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 400, unit: 'ml' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Sweat the leek, add the diced potato and the stock, simmer 20 minutes.',
      'Blend the chickpeas smooth and stir them in.',
      'Add the shredded kale and cook five minutes more.',
    ].join('\n'),
  },
  {
    slug: 'mediterranean-soy-strips',
    title: 'Mediterranean Soy Strips with Eggplant',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['vegan'],
    blurb: 'Soy strips or tofu, eggplant and tomato in one pan.',
    ingredients: [
      { name: 'Tofu', quantity: 120, unit: 'g' },
      { name: 'Eggplant', quantity: 150, unit: 'g' },
      { name: 'Tomato', quantity: 150, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Oregano', quantity: 2, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Sear the strips until browned on both sides and set them aside.',
      'Cook the eggplant in the same pan until soft.',
      'Add the tomatoes, garlic and oregano and simmer 10 minutes.',
      'Return the strips and cook them through in the sauce.',
    ].join('\n'),
  },
  {
    slug: 'stuffed-zucchini-cannellini',
    title: 'Cannellini-Stuffed Zucchini',
    minutes: 45,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Hollow the zucchini, use the flesh in the filling.',
    ingredients: [
      { name: 'Zucchini', quantity: 250, unit: 'g' },
      { name: 'Cannellini Beans', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 20, unit: 'g' },
      { name: 'Nutritional Yeast', quantity: 10, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Halve the zucchini and scoop out the centres; chop the flesh.',
      'Mash the beans with the softened onion, the zucchini flesh and the herbs.',
      'Fill the halves, top with breadcrumbs and nutritional yeast.',
      'Bake 25 minutes at 200 C until the top is crisp.',
    ].join('\n'),
  },
  {
    slug: 'marinated-tempeh',
    title: 'Sticky Marinated Tempeh',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'Boil it first to take the bitterness out, then let the marinade thicken on it.',
    ingredients: [
      { name: 'Tempeh', quantity: 120, unit: 'g' },
      { name: 'Soy Sauce', quantity: 25, unit: 'ml' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Ginger', quantity: 6, unit: 'g' },
      { name: 'Curry Powder', quantity: 3, unit: 'g' },
      { name: 'Lemon', quantity: 10, unit: 'g' },
      { name: 'Maple Syrup', quantity: 12, unit: 'ml' },
      { name: 'Flour', quantity: 5, unit: 'g' },
    ],
    procedure: [
      'Boil the tempeh 10 minutes in water with soy sauce, garlic and ginger.',
      'Marinate it in soy sauce, garlic, curry, lemon, ginger and maple syrup.',
      'Crisp it in a pan or air fryer.',
      'Thicken the leftover marinade with a little flour and pour it back over.',
    ].join('\n'),
  },
  {
    slug: 'golden-soy-chunks',
    title: 'Golden Soy Chunks',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['vegan', 'cheap'],
    blurb: 'Rehydrated in stock, then fried hard so the edges go crisp.',
    ingredients: [
      { name: 'Soy Chunks', quantity: 60, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 300, unit: 'ml' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Black Pepper', quantity: 2, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Rehydrate the chunks in hot stock, then squeeze them dry.',
      'Fry them in the oil without moving them, so they colour.',
      'Add the rosemary, pepper and garlic powder and keep frying until golden.',
    ].join('\n'),
  },
  {
    slug: 'tofu-kebab',
    title: 'Tofu Kebab with Yogurt Sauce',
    minutes: 35,
    course: 'main',
    bulk_prep: false,
    tags: ['sandwich', 'vegetarian'],
    blurb: 'Peeled into ribbons with a peeler so it crisps like shaved kebab.',
    ingredients: [
      { name: 'Tofu', quantity: 130, unit: 'g' },
      { name: 'Smoked Paprika', quantity: 3, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Pita Bread', quantity: 1, unit: 'piece' },
      { name: 'Tomato', quantity: 80, unit: 'g' },
      { name: 'Lettuce', quantity: 40, unit: 'g' },
      { name: 'Greek Yogurt', quantity: 50, unit: 'g' },
      { name: 'Garlic', quantity: 4, unit: 'g' },
    ],
    procedure: [
      'Shave the tofu into thin ribbons with a vegetable peeler.',
      'Toss with the spices and crisp in the air fryer or a hot pan.',
      'Mix the yogurt with garlic, lemon and salt.',
      'Fill the pita with the tofu, tomato, lettuce and sauce.',
    ].join('\n'),
  },
  {
    slug: 'glazed-eggplant-quark',
    title: 'Glazed Eggplant on Whipped Feta',
    minutes: 35,
    course: 'main',
    bulk_prep: false,
    tags: ['vegetarian'],
    blurb: 'Soy and maple glaze, thickened with cornstarch, over cold whipped cheese.',
    ingredients: [
      { name: 'Eggplant', quantity: 200, unit: 'g' },
      { name: 'Soy Sauce', quantity: 20, unit: 'ml' },
      { name: 'Maple Syrup', quantity: 15, unit: 'ml' },
      { name: 'White Wine Vinegar', quantity: 10, unit: 'ml' },
      { name: 'Cornstarch', quantity: 5, unit: 'g' },
      { name: 'Feta', quantity: 40, unit: 'g' },
      { name: 'Quark', quantity: 60, unit: 'g' },
      { name: 'Mint', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Roast the eggplant wedges until soft and browned.',
      'Reduce the soy, maple and vinegar with the cornstarch into a glaze.',
      'Whip the feta with the quark until smooth and spread it on the plate.',
      'Pile on the glazed eggplant and finish with mint.',
    ].join('\n'),
  },
  {
    slug: 'summer-rolls',
    title: 'Summer Rolls with Marinated Tofu',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['vegan'],
    blurb: 'No cooking beyond the noodles, and they travel well.',
    ingredients: [
      { name: 'Rice Paper', quantity: 3, unit: 'piece' },
      { name: 'Tofu', quantity: 100, unit: 'g' },
      { name: 'Rice Noodles', quantity: 50, unit: 'g' },
      { name: 'Carrot', quantity: 60, unit: 'g' },
      { name: 'Cucumber', quantity: 60, unit: 'g' },
      { name: 'Mint', quantity: 3, unit: 'g' },
      { name: 'Soy Sauce', quantity: 15, unit: 'ml' },
      { name: 'Peanuts', quantity: 15, unit: 'g' },
    ],
    procedure: [
      'Marinate the tofu strips in soy sauce and sear them.',
      'Soak the noodles and cut the carrot and cucumber into matchsticks.',
      'Soften one sheet of rice paper at a time and roll tightly.',
      'Serve with a dip of soy sauce, lime and crushed peanuts.',
    ].join('\n'),
  },
  {
    slug: 'falafel',
    title: 'Falafel',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Soaked chickpeas, never cooked ones -- that is the whole trick.',
    ingredients: [
      { name: 'Chickpeas', quantity: 130, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Parsley', quantity: 10, unit: 'g' },
      { name: 'Cilantro', quantity: 10, unit: 'g' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Flour', quantity: 10, unit: 'g' },
      { name: 'Vegetable Oil', quantity: 20, unit: 'ml' },
    ],
    procedure: [
      'Blitz soaked (not cooked) chickpeas with the onion, garlic and herbs.',
      'Season with cumin and salt and bind with a little flour; rest 30 minutes.',
      'Shape into balls and fry or air-fry until deep brown.',
    ].join('\n'),
  },
  {
    slug: 'tofu-pad-thai',
    title: 'Tofu Pad Thai',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['noodles', 'vegetarian'],
    blurb: 'Everything prepped before the wok goes on -- it cooks in four minutes.',
    ingredients: [
      { name: 'Rice Noodles', quantity: 90, unit: 'g' },
      { name: 'Tofu', quantity: 100, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Spring Onion', quantity: 30, unit: 'g' },
      { name: 'Peanuts', quantity: 20, unit: 'g' },
      { name: 'Fish Sauce', quantity: 10, unit: 'ml' },
      { name: 'Lime', quantity: 15, unit: 'g' },
      { name: 'Brown Sugar', quantity: 8, unit: 'g' },
    ],
    procedure: [
      'Soak the noodles until pliable but not soft.',
      'Fry the tofu until crisp, push it aside and scramble the egg.',
      'Add the noodles with the fish sauce, sugar and lime and toss over high heat.',
      'Finish with spring onion and crushed peanuts.',
    ].join('\n'),
  },
  {
    slug: 'chana-masala',
    title: 'Chana Masala',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['curry', 'vegan', 'cheap', 'spicy'],
    blurb: 'Better the next day, which is the point of making a pot of it.',
    ingredients: [
      { name: 'Chickpeas', quantity: 150, unit: 'g' },
      { name: 'Canned Tomatoes', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 70, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Ginger', quantity: 6, unit: 'g' },
      { name: 'Curry Powder', quantity: 5, unit: 'g' },
      { name: 'Turmeric', quantity: 2, unit: 'g' },
      { name: 'Vegetable Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Brown the onion properly, then add the garlic and ginger.',
      'Toast the spices in the oil for a minute.',
      'Add the tomatoes and cook them down before the chickpeas go in.',
      'Simmer 20 minutes, crushing some chickpeas to thicken it.',
    ].join('\n'),
  },
  {
    slug: 'coconut-chicken-curry',
    title: 'Coconut Chicken Curry',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['curry', 'meat'],
    blurb: 'One pot, and it freezes.',
    ingredients: [
      { name: 'Chicken Thigh', quantity: 180, unit: 'g' },
      { name: 'Coconut Milk', quantity: 150, unit: 'ml' },
      { name: 'Curry Paste', quantity: 20, unit: 'g' },
      { name: 'Onion', quantity: 60, unit: 'g' },
      { name: 'Bell Pepper', quantity: 80, unit: 'g' },
      { name: 'Ginger', quantity: 5, unit: 'g' },
      { name: 'Vegetable Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Brown the chicken pieces and set them aside.',
      'Fry the onion, pepper, ginger and curry paste until fragrant.',
      'Add the coconut milk, return the chicken and simmer 20 minutes.',
    ].join('\n'),
  },
  {
    slug: 'shakshuka',
    title: 'Shakshuka',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['vegetarian', 'cheap', 'spicy'],
    blurb: 'Breakfast, lunch or dinner, cooked in the pan it is served from.',
    ingredients: [
      { name: 'Canned Tomatoes', quantity: 200, unit: 'g' },
      { name: 'Bell Pepper', quantity: 80, unit: 'g' },
      { name: 'Onion', quantity: 60, unit: 'g' },
      { name: 'Egg', quantity: 2, unit: 'piece' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Paprika', quantity: 2, unit: 'g' },
      { name: 'Chili Flakes', quantity: 1, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Soften the onion and pepper, then add the spices.',
      'Pour in the tomatoes and reduce until thick.',
      'Make wells, crack in the eggs, cover and cook until just set.',
    ].join('\n'),
  },
  {
    slug: 'pan-seared-steak',
    title: 'Pan-Seared Steak',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['meat', 'quick'],
    blurb: 'Hot pan, dry meat, and let it rest before cutting.',
    ingredients: [
      { name: 'Beef Steak', quantity: 220, unit: 'g' },
      { name: 'Butter', quantity: 15, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Black Pepper', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Take the steak out of the fridge early and pat it dry.',
      'Sear in a very hot pan without moving it, then turn once.',
      'Add the butter, garlic and rosemary and baste for a minute.',
      'Rest it five minutes before slicing.',
    ].join('\n'),
  },
  {
    slug: 'roast-chicken-thighs',
    title: 'Roast Chicken Thighs with Lemon',
    minutes: 50,
    course: 'main',
    bulk_prep: true,
    tags: ['roast', 'meat'],
    blurb: 'Skin side up, one tray, no turning.',
    ingredients: [
      { name: 'Chicken Thigh', quantity: 220, unit: 'g' },
      { name: 'Lemon', quantity: 40, unit: 'g' },
      { name: 'Potato', quantity: 150, unit: 'g' },
      { name: 'Rosemary', quantity: 3, unit: 'g' },
      { name: 'Garlic', quantity: 8, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Toss the potatoes with oil, garlic and rosemary in a tray.',
      'Sit the salted thighs on top, skin side up, with lemon wedges.',
      'Roast 45 minutes at 200 C without turning anything.',
    ].join('\n'),
  },
  {
    slug: 'baked-salmon-herbs',
    title: 'Baked Salmon with Herbs',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['quick'],
    blurb: 'Fifteen minutes in the oven and it is done.',
    ingredients: [
      { name: 'Salmon', quantity: 180, unit: 'g' },
      { name: 'Lemon', quantity: 20, unit: 'g' },
      { name: 'Parsley', quantity: 3, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Garlic', quantity: 4, unit: 'g' },
    ],
    procedure: [
      'Sit the fillet on foil with oil, garlic, lemon and herbs.',
      'Bake 15 minutes at 190 C, until it just flakes.',
      'Squeeze over more lemon at the table.',
    ].join('\n'),
  },
  {
    slug: 'zucchini-frittata',
    title: 'Zucchini Frittata',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['vegetarian', 'quick', 'cheap'],
    blurb: 'Cold the next day in a sandwich, which is arguably better.',
    ingredients: [
      { name: 'Egg', quantity: 3, unit: 'piece' },
      { name: 'Zucchini', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 40, unit: 'g' },
      { name: 'Parmesan', quantity: 20, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Saute the sliced zucchini and onion until they take colour.',
      'Beat the eggs with the parmesan and plenty of salt.',
      'Pour over, cook low until nearly set, then flip or finish under the grill.',
    ].join('\n'),
  },
  {
    slug: 'pizza-margherita',
    title: 'Pizza Margherita',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['pizza', 'vegetarian'],
    blurb: 'Hottest oven you have; the dough can rise while you are at work.',
    ingredients: [
      { name: 'Flour', quantity: 150, unit: 'g' },
      { name: 'Passata', quantity: 80, unit: 'g' },
      { name: 'Mozzarella', quantity: 80, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Knead flour, water, salt and a little yeast and let it rise slowly.',
      'Stretch by hand, spread the passata thinly, salt it.',
      'Bake as hot as the oven goes, adding the mozzarella halfway.',
      'Basil and oil go on after it comes out.',
    ].join('\n'),
  },
  {
    slug: 'lentil-vegetable-stew',
    title: 'Lentil and Vegetable Stew',
    minutes: 50,
    course: 'main',
    bulk_prep: true,
    tags: ['stew', 'vegan', 'cheap'],
    blurb: 'The cheapest pot in the book and it keeps four days.',
    ingredients: [
      { name: 'Lentils', quantity: 120, unit: 'g' },
      { name: 'Carrot', quantity: 80, unit: 'g' },
      { name: 'Celery', quantity: 40, unit: 'g' },
      { name: 'Onion', quantity: 60, unit: 'g' },
      { name: 'Canned Tomatoes', quantity: 150, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 300, unit: 'ml' },
      { name: 'Bay Leaf', quantity: 1, unit: 'piece' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Sweat the diced vegetables in the oil.',
      'Add the lentils, tomatoes, stock and bay leaf.',
      'Simmer 35 minutes until the lentils fall apart at the edges.',
    ].join('\n'),
  },
  // --- sides ---------------------------------------------------------
  {
    slug: 'lentil-hummus-sundried-tomato',
    title: 'Lentil Hummus with Sun-dried Tomatoes',
    minutes: 20,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Lentils instead of chickpeas, hazelnuts instead of half the tahini.',
    ingredients: [
      { name: 'Lentils', quantity: 100, unit: 'g' },
      { name: 'Sun-dried Tomatoes', quantity: 25, unit: 'g' },
      { name: 'Soy Sauce', quantity: 5, unit: 'ml' },
      { name: 'Hazelnuts', quantity: 20, unit: 'g' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
      { name: 'Lemon', quantity: 10, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Blend the cooked lentils with the sun-dried tomatoes and hazelnuts.',
      'Add a splash of soy sauce, the thyme and a little oil.',
      'Grate lemon zest over the top: it carries the flavour without more oil or tahini.',
    ].join('\n'),
  },
  {
    slug: 'roasted-chickpea-hummus',
    title: 'Roasted Chickpea Hummus',
    minutes: 40,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Half the chickpeas roasted with spices first, which changes everything.',
    ingredients: [
      { name: 'Chickpeas', quantity: 140, unit: 'g' },
      { name: 'Smoked Paprika', quantity: 3, unit: 'g' },
      { name: 'Paprika', quantity: 2, unit: 'g' },
      { name: 'Oregano', quantity: 2, unit: 'g' },
      { name: 'Curry Powder', quantity: 2, unit: 'g' },
      { name: 'Chili Flakes', quantity: 0.5, unit: 'g' },
      { name: 'Tahini', quantity: 15, unit: 'g' },
      { name: 'Lemon', quantity: 15, unit: 'g' },
    ],
    procedure: [
      'Roast half the chickpeas with garlic powder, both paprikas, oregano, curry and a pinch of chili.',
      'Blend them with the plain chickpeas, the tahini, lemon juice and water.',
      'Finish with grated lemon zest rather than more tahini or oil.',
    ].join('\n'),
  },
  {
    slug: 'classic-hummus',
    title: 'Classic Hummus',
    minutes: 15,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Ice water while blending is what makes it pale and fluffy.',
    ingredients: [
      { name: 'Chickpeas', quantity: 150, unit: 'g' },
      { name: 'Tahini', quantity: 25, unit: 'g' },
      { name: 'Lemon', quantity: 20, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Blend the tahini with the lemon juice and garlic first, until it seizes and loosens.',
      'Add the chickpeas and blend long, adding ice water until it is silky.',
      'Season, pour over oil, grate on lemon zest.',
    ].join('\n'),
  },
  {
    slug: 'babaganoush',
    title: 'Babaganoush',
    minutes: 45,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Halved and roasted rather than blackened whole -- less mess, same smoke.',
    ingredients: [
      { name: 'Eggplant', quantity: 300, unit: 'g' },
      { name: 'Tahini', quantity: 25, unit: 'g' },
      { name: 'Lemon', quantity: 20, unit: 'g' },
      { name: 'Garlic', quantity: 4, unit: 'g' },
      { name: 'Olive Oil', quantity: 8, unit: 'ml' },
    ],
    procedure: [
      'Halve the eggplants and roast them cut side down until collapsed.',
      'Peel off the skin and drain the flesh.',
      'Mix, do not blend, with the tahini, lemon and a little oil.',
    ].join('\n'),
  },
  {
    slug: 'caramelised-onions-peppers',
    title: 'Caramelised Onions and Peppers',
    minutes: 30,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Sugar only, no vinegar. Goes on everything.',
    ingredients: [
      { name: 'Onion', quantity: 150, unit: 'g' },
      { name: 'Bell Pepper', quantity: 150, unit: 'g' },
      { name: 'Sugar', quantity: 8, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Slice both thinly and start them in oil over medium heat.',
      'When they soften, add the sugar and salt.',
      'Keep going, low, until they are jammy and deep gold.',
    ].join('\n'),
  },
  {
    slug: 'celeriac-chips',
    title: 'Smoked Paprika Celeriac Chips',
    minutes: 35,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'cheap'],
    blurb: 'Crisper than potato and nobody expects them.',
    ingredients: [
      { name: 'Celeriac', quantity: 250, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Smoked Paprika', quantity: 3, unit: 'g' },
      { name: 'Black Pepper', quantity: 1, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
    ],
    procedure: [
      'Cut the celeriac into batons and dry them well.',
      'Toss with oil, rosemary, smoked paprika, pepper and salt.',
      'Roast or air-fry at 200 C until the edges are dark.',
    ].join('\n'),
  },
  {
    slug: 'peperonata',
    title: 'Peperonata',
    minutes: 40,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan', 'cheap'],
    blurb: 'Better lukewarm the next day.',
    ingredients: [
      { name: 'Bell Pepper', quantity: 250, unit: 'g' },
      { name: 'Onion', quantity: 80, unit: 'g' },
      { name: 'Tomato', quantity: 100, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Basil', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Cook the sliced onion until soft, then add the peppers.',
      'Add the tomato and cook slowly, covered, for 30 minutes.',
      'Season well and finish with basil.',
    ].join('\n'),
  },
  {
    slug: 'caponata',
    title: 'Caponata',
    minutes: 50,
    course: 'side',
    bulk_prep: true,
    tags: ['vegan'],
    blurb: 'Sweet, sour, and it improves for three days.',
    ingredients: [
      { name: 'Eggplant', quantity: 250, unit: 'g' },
      { name: 'Celery', quantity: 60, unit: 'g' },
      { name: 'Onion', quantity: 60, unit: 'g' },
      { name: 'Passata', quantity: 100, unit: 'g' },
      { name: 'Olives', quantity: 30, unit: 'g' },
      { name: 'Capers', quantity: 10, unit: 'g' },
      { name: 'White Wine Vinegar', quantity: 15, unit: 'ml' },
      { name: 'Sugar', quantity: 8, unit: 'g' },
      { name: 'Olive Oil', quantity: 20, unit: 'ml' },
    ],
    procedure: [
      'Fry the eggplant cubes until browned and drain them.',
      'Soften the celery and onion, then add the passata, olives and capers.',
      'Return the eggplant, add the vinegar and sugar and cook until sticky.',
    ].join('\n'),
  },
  {
    slug: 'mashed-potatoes',
    title: 'Mashed Potatoes',
    minutes: 30,
    course: 'side',
    bulk_prep: false,
    tags: ['vegetarian', 'cheap'],
    blurb: 'Warm the milk first; cold milk makes it gluey.',
    ingredients: [
      { name: 'Potato', quantity: 250, unit: 'g' },
      { name: 'Butter', quantity: 25, unit: 'g' },
      { name: 'Milk', quantity: 60, unit: 'ml' },
      { name: 'Nutmeg', quantity: 0.5, unit: 'g' },
      { name: 'Salt', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Boil the potatoes whole in salted water, then peel and rice them.',
      'Beat in the butter, then the warm milk.',
      'Season with salt and a scrape of nutmeg.',
    ].join('\n'),
  },
  {
    slug: 'rosemary-roasted-potatoes',
    title: 'Rosemary Roasted Potatoes',
    minutes: 45,
    course: 'side',
    bulk_prep: false,
    tags: ['roast', 'vegan', 'cheap'],
    blurb: 'Parboil and rough them up -- that is where the crust comes from.',
    ingredients: [
      { name: 'Potato', quantity: 250, unit: 'g' },
      { name: 'Rosemary', quantity: 3, unit: 'g' },
      { name: 'Garlic', quantity: 8, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Salt', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Parboil the chunks 8 minutes, drain, and shake them in the pan.',
      'Toss with hot oil, salt, rosemary and unpeeled garlic.',
      'Roast at 210 C for 35 minutes, turning once.',
    ].join('\n'),
  },
  {
    slug: 'boiled-eggs',
    title: 'Boiled Eggs',
    minutes: 12,
    course: 'side',
    bulk_prep: false,
    tags: ['vegetarian', 'quick', 'cheap'],
    blurb: 'Seven minutes for jammy, ten for firm.',
    ingredients: [
      { name: 'Egg', quantity: 2, unit: 'piece' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Lower the eggs into already boiling water.',
      'Seven minutes for a jammy yolk, ten for hard.',
      'Straight into cold water so they peel cleanly.',
    ].join('\n'),
  },
  {
    slug: 'steamed-broccoli',
    title: 'Steamed Broccoli',
    minutes: 15,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Stop while it is still bright green.',
    ingredients: [
      { name: 'Broccoli', quantity: 200, unit: 'g' },
      { name: 'Olive Oil', quantity: 8, unit: 'ml' },
      { name: 'Lemon', quantity: 10, unit: 'g' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Steam the florets 5 to 6 minutes, until a knife just goes in.',
      'Dress warm with oil, lemon and salt.',
    ].join('\n'),
  },
  {
    slug: 'boiled-potatoes',
    title: 'Boiled Potatoes with Olive Oil',
    minutes: 25,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Salt the water like soup and dress them while hot.',
    ingredients: [
      { name: 'Potato', quantity: 250, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
      { name: 'Parsley', quantity: 3, unit: 'g' },
      { name: 'Salt', quantity: 4, unit: 'g' },
    ],
    procedure: [
      'Boil the potatoes whole in well-salted water until tender.',
      'Halve them and dress immediately with oil, salt and parsley.',
    ].join('\n'),
  },
  {
    slug: 'pan-fried-zucchini',
    title: 'Pan-Fried Zucchini with Mint',
    minutes: 15,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'High heat, one layer, do not stir too soon.',
    ingredients: [
      { name: 'Zucchini', quantity: 250, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Mint', quantity: 3, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
    ],
    procedure: [
      'Slice the zucchini into rounds and get the pan properly hot.',
      'Fry in one layer until the undersides are brown, then turn.',
      'Add the garlic at the end and finish with torn mint.',
    ].join('\n'),
  },
  {
    slug: 'sauteed-spinach-garlic',
    title: 'Sauteed Spinach with Garlic',
    minutes: 10,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Two minutes from raw to done.',
    ingredients: [
      { name: 'Spinach', quantity: 200, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Lemon', quantity: 8, unit: 'g' },
    ],
    procedure: [
      'Warm the sliced garlic in the oil.',
      'Add the spinach in handfuls and toss until just wilted.',
      'Salt and lemon off the heat.',
    ].join('\n'),
  },
  {
    slug: 'roasted-carrots-cumin',
    title: 'Roasted Carrots with Cumin',
    minutes: 35,
    course: 'side',
    bulk_prep: false,
    tags: ['roast', 'vegan', 'cheap'],
    blurb: 'They go sweet enough to eat like sweets.',
    ingredients: [
      { name: 'Carrot', quantity: 250, unit: 'g' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Honey', quantity: 8, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
    ],
    procedure: [
      'Halve the carrots lengthways and toss with oil, cumin and salt.',
      'Roast 30 minutes at 200 C.',
      'Brush with a little honey for the last five minutes.',
    ].join('\n'),
  },
  {
    slug: 'green-beans-garlic',
    title: 'Green Beans with Garlic',
    minutes: 20,
    course: 'side',
    bulk_prep: false,
    tags: ['vegan', 'quick', 'cheap'],
    blurb: 'Boiled, then finished in the pan so they pick up some colour.',
    ingredients: [
      { name: 'Green Beans', quantity: 200, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Chili Flakes', quantity: 0.5, unit: 'g' },
    ],
    procedure: [
      'Boil the beans in salted water until just tender, then drain.',
      'Finish them in a hot pan with the garlic and chili flakes.',
    ].join('\n'),
  },
  {
    slug: 'green-salad',
    title: 'Green Salad',
    minutes: 10,
    course: 'side',
    bulk_prep: false,
    tags: ['salad', 'vegan', 'quick', 'cheap'],
    blurb: 'Dress it at the table, not before.',
    ingredients: [
      { name: 'Lettuce', quantity: 80, unit: 'g' },
      { name: 'Rocket', quantity: 30, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
      { name: 'White Wine Vinegar', quantity: 6, unit: 'ml' },
      { name: 'Salt', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Wash and dry the leaves properly -- wet leaves will not hold dressing.',
      'Whisk oil, vinegar and salt and toss at the last moment.',
    ].join('\n'),
  },
  {
    slug: 'tomato-cucumber-salad',
    title: 'Tomato and Cucumber Salad',
    minutes: 10,
    course: 'side',
    bulk_prep: false,
    tags: ['salad', 'vegan', 'quick', 'cheap'],
    blurb: 'Salt the tomatoes first and use the juice as the dressing.',
    ingredients: [
      { name: 'Tomato', quantity: 200, unit: 'g' },
      { name: 'Cucumber', quantity: 100, unit: 'g' },
      { name: 'Red Onion', quantity: 30, unit: 'g' },
      { name: 'Olive Oil', quantity: 12, unit: 'ml' },
      { name: 'Oregano', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Cut the tomatoes into wedges, salt them and let them sit ten minutes.',
      'Add the cucumber and thinly sliced red onion.',
      'Dress with oil and oregano, using the tomato juices.',
    ].join('\n'),
  },
  {
    slug: 'simple-rice-pilaf',
    title: 'Simple Rice Pilaf',
    minutes: 25,
    course: 'side',
    bulk_prep: false,
    tags: ['rice', 'vegan', 'quick', 'cheap'],
    blurb: 'Toast the rice first and it will not turn to porridge.',
    ingredients: [
      { name: 'Basmati Rice', quantity: 80, unit: 'g' },
      { name: 'Onion', quantity: 40, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 160, unit: 'ml' },
      { name: 'Bay Leaf', quantity: 1, unit: 'piece' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Soften the onion, then toast the rinsed rice in the oil.',
      'Add twice its volume of stock and the bay leaf.',
      'Cover, cook 12 minutes, then rest 10 off the heat before forking through.',
    ].join('\n'),
  },
]

// The modal's sections are the three courses: a new user picks what to cook
// for a slot, and the planner draws mains and sides from separate pools.
export const COURSE_SECTIONS = [
  { key: 'first-course', label: 'First courses' },
  { key: 'main', label: 'Mains' },
  { key: 'side', label: 'Sides' },
]

// Format tags order the recipes inside a section, so pasta sits next to pasta.
// A recipe carrying none of them sorts after those that do.
const FORMAT_ORDER = new Map([
  'pasta', 'soup', 'risotto', 'curry', 'stew', 'salad', 'noodles', 'gnocchi',
  'rice', 'sandwich', 'roast', 'pizza',
].map((tag, index) => [tag, index]))

function formatRank(recipe) {
  for (const tag of recipe.tags) {
    if (FORMAT_ORDER.has(tag)) return FORMAT_ORDER.get(tag)
  }
  return FORMAT_ORDER.size
}

// Returns [{ key, label, recipes }] in COURSE_SECTIONS order, skipping empty
// sections. One pass over the recipes rather than one filter per section.
export function groupStarterRecipes(recipes) {
  const buckets = new Map(COURSE_SECTIONS.map((section) => [section.key, []]))
  recipes.forEach((recipe) => buckets.get(recipe.course).push(recipe))
  return COURSE_SECTIONS.map((section) => ({
    ...section,
    recipes: buckets.get(section.key).sort((a, b) => formatRank(a) - formatRank(b)),
  })).filter((section) => section.recipes.length > 0)
}
