// The starter recipe pack offered to an account whose recipe book is still
// empty (see StarterRecipesModal). Everyday, low-effort dishes: the point is
// that a new user can plan a week without typing a recipe first.
//
// Two rules the tests enforce, both about not damaging the seeded account:
//
// * every `name` must already exist in backend/data/system_ingredients.json,
//   so importing reuses the account's own ingredient rows (with their real
//   seasonality and units) instead of inventing all-year ones;
// * every tag must be one of the system tags seeded by
//   backend/mealplanner/seed.py — the pack introduces no tag vocabulary.
//
// Quantities are **per person**, the basis models.Recipe stores and the
// shopping list scales from. `minutes` is shown in the modal to help the user
// choose and is deliberately not persisted: Recipe has no time column.

export const STARTER_RECIPES = [
  // --- pasta ---------------------------------------------------------
  {
    slug: 'creamy-pasta-e-ceci',
    title: 'Creamy Pasta e Ceci',
    minutes: 30,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegetarian', 'cheap'],
    blurb: 'Half the chickpeas blended for a silky sauce, no cream.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Chickpeas', quantity: 130, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Tomato Paste', quantity: 10, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Warm the oil with the garlic and rosemary, then stir in the tomato paste.',
      'Add the chickpeas and enough water to cover; simmer 10 minutes.',
      'Blend half the chickpeas back into the pot for the creamy base.',
      'Cook the pasta straight in the pot, adding water as it absorbs.',
    ].join('\n'),
  },
  {
    slug: 'tuna-cherry-tomato-pasta',
    title: 'Tuna and Cherry Tomato Pasta',
    minutes: 20,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'quick', 'cheap'],
    blurb: 'Pure storecupboard — always makeable.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Canned Tuna', quantity: 80, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 120, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
      { name: 'Parsley', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Burst the cherry tomatoes in oil with the garlic over high heat.',
      'Add the drained tuna and break it up; season.',
      'Toss the drained pasta through with a splash of its water and the parsley.',
    ].join('\n'),
  },
  {
    slug: 'pasta-alla-norma',
    title: 'Pasta alla Norma',
    minutes: 35,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'vegetarian'],
    blurb: 'Pan-fried eggplant, simple tomato sauce, ricotta salata.',
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Eggplant', quantity: 150, unit: 'g' },
      { name: 'Passata', quantity: 150, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
      { name: 'Ricotta Salata', quantity: 20, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Cube the eggplant and fry in oil until deep golden; drain on paper.',
      'Simmer the passata with the garlic for 10 minutes.',
      'Toss with the pasta and eggplant, grate over the ricotta salata, tear in basil.',
    ].join('\n'),
  },
  {
    slug: 'spaghetti-alle-vongole',
    title: 'Spaghetti alle Vongole',
    minutes: 25,
    course: 'first-course',
    bulk_prep: false,
    tags: ['pasta', 'quick'],
    blurb: 'Simplified: pre-purged clams, garlic, white wine.',
    ingredients: [
      { name: 'Spaghetti', quantity: 90, unit: 'g' },
      { name: 'Clams', quantity: 250, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'White Wine', quantity: 40, unit: 'ml' },
      { name: 'Parsley', quantity: 4, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Chili Flakes', quantity: 1, unit: 'g' },
    ],
    procedure: [
      'Start the spaghetti; it finishes in the pan.',
      'Open the clams in a covered pan with oil, garlic, chili and the wine.',
      'Drain the pasta a minute early and finish it in the clam liquid with parsley.',
    ].join('\n'),
  },

  // --- soup ----------------------------------------------------------
  {
    slug: 'pumpkin-potato-soup',
    title: 'Pumpkin and Potato Soup with Croutons',
    minutes: 35,
    course: 'first-course',
    bulk_prep: true,
    tags: ['soup', 'vegetarian', 'cheap'],
    blurb: 'Blended smooth and freezes in portions.',
    ingredients: [
      { name: 'Pumpkin', quantity: 250, unit: 'g' },
      { name: 'Potato', quantity: 100, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Vegetable Stock', quantity: 300, unit: 'ml' },
      { name: 'Bread', quantity: 1, unit: 'piece' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Soften the onion, add the diced pumpkin and potato, cover with stock.',
      'Simmer 20 minutes, until everything crushes against the pan.',
      'Blend smooth; toast cubed bread in oil and scatter on top.',
    ].join('\n'),
  },

  // --- risotto -------------------------------------------------------
  {
    slug: 'mushroom-risotto',
    title: 'Mushroom Risotto',
    minutes: 30,
    course: 'first-course',
    bulk_prep: false,
    tags: ['risotto', 'vegetarian'],
    blurb: 'One pan, ordinary supermarket mushrooms.',
    ingredients: [
      { name: 'Arborio Rice', quantity: 90, unit: 'g' },
      { name: 'Mushroom', quantity: 120, unit: 'g' },
      { name: 'Onion', quantity: 30, unit: 'g' },
      { name: 'White Wine', quantity: 40, unit: 'ml' },
      { name: 'Vegetable Stock', quantity: 350, unit: 'ml' },
      { name: 'Parmesan', quantity: 20, unit: 'g' },
      { name: 'Butter', quantity: 10, unit: 'g' },
    ],
    procedure: [
      'Brown the mushrooms hard, then set half aside for the top.',
      'Soften the onion, toast the rice, deglaze with the wine.',
      'Add hot stock a ladle at a time for 18 minutes.',
      'Off the heat, beat in the butter and parmesan and rest 2 minutes.',
    ].join('\n'),
  },

  // --- curry ---------------------------------------------------------
  {
    slug: 'red-lentil-coconut-curry',
    title: 'Red Lentil and Coconut Curry',
    minutes: 30,
    course: 'main',
    bulk_prep: true,
    tags: ['curry', 'vegan', 'cheap'],
    blurb: 'One pot, cooks itself, good with basmati.',
    ingredients: [
      { name: 'Red Lentils', quantity: 90, unit: 'g' },
      { name: 'Coconut Milk', quantity: 120, unit: 'ml' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Ginger', quantity: 5, unit: 'g' },
      { name: 'Curry Powder', quantity: 5, unit: 'g' },
      { name: 'Turmeric', quantity: 2, unit: 'g' },
      { name: 'Basmati Rice', quantity: 70, unit: 'g' },
    ],
    procedure: [
      'Fry the onion, garlic, ginger and spices until fragrant.',
      'Add the rinsed lentils, coconut milk and 200 ml water.',
      'Simmer 20 minutes, stirring now and then, while the rice cooks.',
    ].join('\n'),
  },
  {
    slug: 'coconut-chicken-curry',
    title: 'Coconut Chicken Curry',
    minutes: 35,
    course: 'main',
    bulk_prep: false,
    tags: ['curry'],
    blurb: 'Mild and sweet — children eat it happily.',
    ingredients: [
      { name: 'Chicken Thigh', quantity: 150, unit: 'g' },
      { name: 'Coconut Milk', quantity: 120, unit: 'ml' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Curry Paste', quantity: 15, unit: 'g' },
      { name: 'Bell Pepper', quantity: 70, unit: 'g' },
      { name: 'Basmati Rice', quantity: 70, unit: 'g' },
    ],
    procedure: [
      'Brown the diced chicken, lift it out, soften the onion and pepper.',
      'Fry the curry paste a minute, return the chicken, pour in the coconut milk.',
      'Simmer 15 minutes and serve over the rice.',
    ].join('\n'),
  },

  // --- stew ----------------------------------------------------------
  {
    slug: 'chili-sin-carne',
    title: 'Chili sin Carne',
    minutes: 35,
    course: 'main',
    bulk_prep: true,
    tags: ['stew', 'vegan', 'spicy', 'cheap'],
    blurb: 'Black beans, corn and spice; better the next day.',
    ingredients: [
      { name: 'Black Beans', quantity: 150, unit: 'g' },
      { name: 'Corn', quantity: 60, unit: 'g' },
      { name: 'Canned Tomatoes', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Bell Pepper', quantity: 70, unit: 'g' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Paprika', quantity: 3, unit: 'g' },
      { name: 'Chili Flakes', quantity: 1, unit: 'g' },
    ],
    procedure: [
      'Soften the onion and pepper, then toast the spices in the pan.',
      'Add the tomatoes, beans and corn and simmer 20 minutes.',
      'Season hard at the end — it needs more salt than you think.',
    ].join('\n'),
  },
  {
    slug: 'chili-con-carne',
    title: 'Chili con Carne',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: ['stew', 'spicy'],
    blurb: 'Mince, beans and spice; reheats even better.',
    ingredients: [
      { name: 'Ground Beef', quantity: 130, unit: 'g' },
      { name: 'Kidney Beans', quantity: 100, unit: 'g' },
      { name: 'Canned Tomatoes', quantity: 150, unit: 'g' },
      { name: 'Onion', quantity: 50, unit: 'g' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Paprika', quantity: 3, unit: 'g' },
      { name: 'Chili Flakes', quantity: 1, unit: 'g' },
    ],
    procedure: [
      'Brown the mince properly, in one layer, before touching it.',
      'Add the onion and spices, then the tomatoes and beans.',
      'Simmer 25 minutes until it thickens.',
    ].join('\n'),
  },
  {
    slug: 'quick-chicken-cacciatora',
    title: 'Quick Chicken Cacciatora',
    minutes: 35,
    course: 'main',
    bulk_prep: false,
    tags: ['stew'],
    blurb: 'Tomato, olives and rosemary; serve with bread or polenta.',
    ingredients: [
      { name: 'Chicken Thigh', quantity: 160, unit: 'g' },
      { name: 'Passata', quantity: 150, unit: 'g' },
      { name: 'Olives', quantity: 30, unit: 'g' },
      { name: 'Rosemary', quantity: 2, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'White Wine', quantity: 40, unit: 'ml' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Brown the chicken skin-side down, then add the garlic and rosemary.',
      'Deglaze with the wine, add the passata and olives.',
      'Cover and simmer 20 minutes, turning once.',
    ].join('\n'),
  },

  // --- salad ---------------------------------------------------------
  {
    slug: 'grilled-chicken-avocado-corn-salad',
    title: 'Grilled Chicken, Avocado and Corn Salad',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['salad', 'quick'],
    blurb: 'A cool one-plate dinner for warm evenings.',
    ingredients: [
      { name: 'Chicken Breast', quantity: 140, unit: 'g' },
      { name: 'Avocado', quantity: 60, unit: 'g' },
      { name: 'Corn', quantity: 60, unit: 'g' },
      { name: 'Lettuce', quantity: 60, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 80, unit: 'g' },
      { name: 'Lime', quantity: 15, unit: 'ml' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Grill the flattened chicken breast 4 minutes a side, then rest and slice.',
      'Toss the leaves, tomato, corn and avocado with lime and oil.',
      'Lay the chicken over the top.',
    ].join('\n'),
  },
  {
    slug: 'grilled-vegetable-feta-couscous',
    title: 'Grilled Vegetable and Feta Couscous',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['salad', 'vegetarian', 'quick'],
    blurb: 'One bowl, warm or cold, no real cooking.',
    ingredients: [
      { name: 'Couscous', quantity: 80, unit: 'g' },
      { name: 'Zucchini', quantity: 80, unit: 'g' },
      { name: 'Bell Pepper', quantity: 80, unit: 'g' },
      { name: 'Eggplant', quantity: 80, unit: 'g' },
      { name: 'Feta', quantity: 40, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
      { name: 'Mint', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Cover the couscous with an equal volume of boiling water; lid it 5 minutes.',
      'Griddle the sliced vegetables in oil until marked.',
      'Fork the couscous through, fold in the vegetables, crumble over feta and mint.',
    ].join('\n'),
  },

  // --- noodles -------------------------------------------------------
  {
    slug: 'pad-thai-style-noodles-tofu',
    title: 'Pad Thai-style Noodles with Tofu',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['noodles', 'vegetarian', 'quick'],
    blurb: 'Rice noodles, egg, peanuts and lime.',
    ingredients: [
      { name: 'Rice Noodles', quantity: 80, unit: 'g' },
      { name: 'Tofu', quantity: 100, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Peanuts', quantity: 20, unit: 'g' },
      { name: 'Lime', quantity: 15, unit: 'ml' },
      { name: 'Soy Sauce', quantity: 15, unit: 'ml' },
      { name: 'Spring Onion', quantity: 20, unit: 'g' },
      { name: 'Sugar', quantity: 5, unit: 'g' },
    ],
    procedure: [
      'Soak the noodles in hot water until pliable, then drain.',
      'Fry the cubed tofu until golden, push aside and scramble the egg in the pan.',
      'Add noodles, soy, sugar and lime; toss hard for a minute.',
      'Finish with crushed peanuts and spring onion.',
    ].join('\n'),
  },

  // --- gnocchi -------------------------------------------------------
  {
    slug: 'gnocchi-alla-sorrentina',
    title: 'Gnocchi alla Sorrentina',
    minutes: 30,
    course: 'first-course',
    bulk_prep: false,
    tags: ['gnocchi', 'vegetarian'],
    blurb: 'Pan then grill, using shop-bought gnocchi.',
    ingredients: [
      { name: 'Gnocchi', quantity: 200, unit: 'g' },
      { name: 'Passata', quantity: 150, unit: 'g' },
      { name: 'Mozzarella', quantity: 60, unit: 'g' },
      { name: 'Parmesan', quantity: 15, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Simmer the passata with oil and basil for 10 minutes.',
      'Boil the gnocchi until they float, then fold into the sauce.',
      'Top with torn mozzarella and parmesan and grill until blistered.',
    ].join('\n'),
  },

  // --- rice ----------------------------------------------------------
  {
    slug: 'salmon-poke-bowl',
    title: 'Salmon Poke Bowl',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['rice', 'quick'],
    blurb: 'Rice, salmon, avocado, edamame — assembly, not cooking.',
    ingredients: [
      { name: 'Rice', quantity: 80, unit: 'g' },
      { name: 'Smoked Salmon', quantity: 100, unit: 'g' },
      { name: 'Avocado', quantity: 60, unit: 'g' },
      { name: 'Edamame', quantity: 50, unit: 'g' },
      { name: 'Cucumber', quantity: 50, unit: 'g' },
      { name: 'Soy Sauce', quantity: 15, unit: 'ml' },
      { name: 'Rice Vinegar', quantity: 10, unit: 'ml' },
      { name: 'Sesame Seeds', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Cook the rice, season it warm with the vinegar, let it cool a little.',
      'Slice the salmon, avocado and cucumber; blanch the edamame.',
      'Arrange over the rice, dress with soy and sesame seeds.',
    ].join('\n'),
  },
  {
    slug: 'baked-teriyaki-tofu-bowl',
    title: 'Baked Teriyaki Tofu Bowl',
    minutes: 35,
    course: 'main',
    bulk_prep: false,
    tags: ['rice', 'vegan'],
    blurb: 'Everything on one tray while the rice cooks.',
    ingredients: [
      { name: 'Tofu', quantity: 150, unit: 'g' },
      { name: 'Broccoli', quantity: 120, unit: 'g' },
      { name: 'Rice', quantity: 80, unit: 'g' },
      { name: 'Soy Sauce', quantity: 20, unit: 'ml' },
      { name: 'Honey', quantity: 10, unit: 'g' },
      { name: 'Ginger', quantity: 5, unit: 'g' },
      { name: 'Sesame Oil', quantity: 5, unit: 'ml' },
    ],
    procedure: [
      'Mix soy, honey, ginger and sesame oil into a glaze.',
      'Toss cubed tofu and broccoli florets in it and roast at 200 °C for 25 minutes.',
      'Serve over the rice with the tray juices poured back over.',
    ].join('\n'),
  },

  // --- sandwich ------------------------------------------------------
  {
    slug: 'chickpea-burger',
    title: 'Chickpea Burger',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['sandwich', 'vegetarian', 'cheap'],
    blurb: 'Blitzed in the processor, fried in a pan, in a bun or with salad.',
    ingredients: [
      { name: 'Chickpeas', quantity: 150, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 30, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Onion', quantity: 30, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Bread', quantity: 1, unit: 'piece' },
      { name: 'Lettuce', quantity: 30, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Pulse the chickpeas with the onion and cumin to a coarse paste.',
      'Work in the egg and breadcrumbs and shape a patty; chill 10 minutes.',
      'Fry 4 minutes a side and build the burger.',
    ].join('\n'),
  },
  {
    slug: 'seitan-kebab',
    title: 'Seitan Kebab',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['sandwich', 'vegan', 'quick'],
    blurb: 'Spiced strips in warm pita with salad.',
    ingredients: [
      { name: 'Seitan', quantity: 130, unit: 'g' },
      { name: 'Pita Bread', quantity: 1, unit: 'piece' },
      { name: 'Paprika', quantity: 3, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Red Onion', quantity: 30, unit: 'g' },
      { name: 'Tomato', quantity: 60, unit: 'g' },
      { name: 'Lettuce', quantity: 40, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Toss seitan strips with the spices and oil; fry hard until crisp at the edges.',
      'Warm the pita and slice the salad thinly.',
      'Fill and eat immediately.',
    ].join('\n'),
  },

  // --- other ---------------------------------------------------------
  {
    slug: 'shakshuka',
    title: 'Shakshuka',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['vegetarian', 'spicy', 'quick', 'cheap'],
    blurb: 'Eggs poached in spiced tomato, eaten from the pan.',
    ingredients: [
      { name: 'Egg', quantity: 2, unit: 'piece' },
      { name: 'Canned Tomatoes', quantity: 200, unit: 'g' },
      { name: 'Bell Pepper', quantity: 70, unit: 'g' },
      { name: 'Onion', quantity: 40, unit: 'g' },
      { name: 'Harissa', quantity: 10, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Bread', quantity: 1, unit: 'piece' },
    ],
    procedure: [
      'Soften the onion and pepper, stir in the harissa and cumin.',
      'Add the tomatoes and reduce for 10 minutes.',
      'Make wells, crack in the eggs, cover until just set. Serve with bread.',
    ].join('\n'),
  },
  {
    slug: 'zucchini-potato-frittata',
    title: 'Zucchini and Potato Frittata',
    minutes: 25,
    course: 'main',
    bulk_prep: true,
    tags: ['vegetarian', 'quick', 'cheap'],
    blurb: 'Make it ahead — just as good cold in a lunchbox.',
    ingredients: [
      { name: 'Egg', quantity: 2, unit: 'piece' },
      { name: 'Zucchini', quantity: 100, unit: 'g' },
      { name: 'Potato', quantity: 100, unit: 'g' },
      { name: 'Parmesan', quantity: 15, unit: 'g' },
      { name: 'Onion', quantity: 30, unit: 'g' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Fry thin potato slices with the onion until tender, then add the zucchini.',
      'Beat the eggs with the parmesan and pour over.',
      'Cook low until nearly set, then flip or finish under the grill.',
    ].join('\n'),
  },
  {
    slug: 'bean-cheese-quesadillas',
    title: 'Bean and Cheese Quesadillas',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['vegetarian', 'quick', 'cheap'],
    blurb: 'Very fast — for the evening you cannot face cooking.',
    ingredients: [
      { name: 'Tortilla', quantity: 2, unit: 'piece' },
      { name: 'Black Beans', quantity: 100, unit: 'g' },
      { name: 'Cheddar Cheese', quantity: 50, unit: 'g' },
      { name: 'Spring Onion', quantity: 20, unit: 'g' },
      { name: 'Paprika', quantity: 2, unit: 'g' },
    ],
    procedure: [
      'Crush the beans with the paprika into a rough paste.',
      'Spread over one tortilla with the cheese and spring onion; top with the second.',
      'Dry-fry 3 minutes a side and cut into wedges.',
    ].join('\n'),
  },
  {
    slug: 'falafel',
    title: 'Falafel',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: ['vegan', 'cheap'],
    blurb: 'Pan-fried, not deep-fried, with tahini sauce.',
    ingredients: [
      { name: 'Chickpeas', quantity: 150, unit: 'g' },
      { name: 'Parsley', quantity: 10, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Cumin', quantity: 3, unit: 'g' },
      { name: 'Flour', quantity: 20, unit: 'g' },
      { name: 'Tahini', quantity: 20, unit: 'g' },
      { name: 'Lemon', quantity: 15, unit: 'ml' },
      { name: 'Vegetable Oil', quantity: 20, unit: 'ml' },
    ],
    procedure: [
      'Blitz the chickpeas with the parsley, garlic and cumin; work in the flour.',
      'Shape flattened balls and fry in shallow oil until dark gold.',
      'Loosen the tahini with the lemon and water and spoon over.',
    ].join('\n'),
  },
  {
    slug: 'crispy-tofu-stir-fry',
    title: 'Crispy Tofu Stir-fry',
    minutes: 20,
    course: 'main',
    bulk_prep: false,
    tags: ['vegan', 'quick'],
    blurb: 'Wok, soy sauce, rice alongside.',
    ingredients: [
      { name: 'Tofu', quantity: 150, unit: 'g' },
      { name: 'Broccoli', quantity: 100, unit: 'g' },
      { name: 'Bell Pepper', quantity: 70, unit: 'g' },
      { name: 'Carrot', quantity: 50, unit: 'g' },
      { name: 'Soy Sauce', quantity: 20, unit: 'ml' },
      { name: 'Ginger', quantity: 5, unit: 'g' },
      { name: 'Sesame Oil', quantity: 5, unit: 'ml' },
      { name: 'Rice', quantity: 70, unit: 'g' },
    ],
    procedure: [
      'Press the tofu dry, cube it and fry until crisp on every face; remove.',
      'Stir-fry the vegetables hot and fast with the ginger.',
      'Return the tofu, splash in the soy and sesame oil, serve with the rice.',
    ].join('\n'),
  },
  {
    slug: 'lemon-chicken-roast-potatoes',
    title: 'Lemon Chicken with Roast Potatoes',
    minutes: 45,
    course: 'main',
    bulk_prep: false,
    tags: ['roast'],
    blurb: 'One tray, no supervision.',
    ingredients: [
      { name: 'Chicken Thigh', quantity: 180, unit: 'g' },
      { name: 'Potato', quantity: 200, unit: 'g' },
      { name: 'Lemon', quantity: 30, unit: 'ml' },
      { name: 'Rosemary', quantity: 3, unit: 'g' },
      { name: 'Garlic', quantity: 6, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Toss the chunked potatoes, chicken, garlic, rosemary, lemon and oil in a tray.',
      'Roast at 200 °C for 40 minutes, turning once halfway.',
    ].join('\n'),
  },
  {
    slug: 'chicken-fajitas',
    title: 'Chicken Fajitas',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['quick', 'spicy'],
    blurb: 'Strips of chicken and pepper, tortillas on the table.',
    ingredients: [
      { name: 'Chicken Breast', quantity: 150, unit: 'g' },
      { name: 'Bell Pepper', quantity: 90, unit: 'g' },
      { name: 'Red Onion', quantity: 50, unit: 'g' },
      { name: 'Tortilla', quantity: 2, unit: 'piece' },
      { name: 'Paprika', quantity: 3, unit: 'g' },
      { name: 'Cumin', quantity: 2, unit: 'g' },
      { name: 'Lime', quantity: 15, unit: 'ml' },
      { name: 'Chili Flakes', quantity: 1, unit: 'g' },
    ],
    procedure: [
      'Toss the chicken strips with the spices and sear them hard.',
      'Add the pepper and onion; keep the pan hot so they char rather than steam.',
      'Squeeze over the lime and let everyone fill their own tortillas.',
    ].join('\n'),
  },
  {
    slug: 'turkey-meatballs-tomato-sauce',
    title: 'Turkey Meatballs in Tomato Sauce',
    minutes: 35,
    course: 'main',
    bulk_prep: true,
    tags: [],
    blurb: 'Light; make a double batch and freeze half.',
    ingredients: [
      { name: 'Ground Turkey', quantity: 140, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 20, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Parmesan', quantity: 15, unit: 'g' },
      { name: 'Passata', quantity: 180, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Basil', quantity: 3, unit: 'g' },
    ],
    procedure: [
      'Mix the turkey with the breadcrumbs, egg and parmesan and roll small balls.',
      'Brown them in a pan, then pour in the passata with the garlic.',
      'Simmer 20 minutes and finish with basil.',
    ].join('\n'),
  },
  {
    slug: 'beef-straccetti-rocket-grana',
    title: 'Beef Straccetti with Rocket and Grana',
    minutes: 15,
    course: 'main',
    bulk_prep: false,
    tags: ['quick'],
    blurb: 'The fastest thing in the book.',
    ingredients: [
      { name: 'Beef Steak', quantity: 150, unit: 'g' },
      { name: 'Rocket', quantity: 40, unit: 'g' },
      { name: 'Parmesan', quantity: 20, unit: 'g' },
      { name: 'Lemon', quantity: 10, unit: 'ml' },
      { name: 'Olive Oil', quantity: 10, unit: 'ml' },
    ],
    procedure: [
      'Slice the beef as thinly as you can and sear it 60 seconds in a smoking pan.',
      'Off the heat, add lemon and oil.',
      'Pile onto the rocket and shave over the parmesan.',
    ].join('\n'),
  },
  {
    slug: 'meatballs-tomato-sauce',
    title: 'Meatballs in Tomato Sauce',
    minutes: 40,
    course: 'main',
    bulk_prep: true,
    tags: [],
    blurb: 'The leftover sauce dresses tomorrow’s pasta.',
    ingredients: [
      { name: 'Ground Beef', quantity: 120, unit: 'g' },
      { name: 'Ground Pork', quantity: 60, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 25, unit: 'g' },
      { name: 'Egg', quantity: 1, unit: 'piece' },
      { name: 'Passata', quantity: 200, unit: 'g' },
      { name: 'Garlic', quantity: 5, unit: 'g' },
      { name: 'Parsley', quantity: 4, unit: 'g' },
    ],
    procedure: [
      'Combine the meats with the breadcrumbs, egg and parsley; roll walnut-sized balls.',
      'Brown all over, then add the passata and garlic.',
      'Simmer gently 25 minutes without stirring too much.',
    ].join('\n'),
  },
  {
    slug: 'sweet-and-sour-pork',
    title: 'Sweet and Sour Pork with Vegetables',
    minutes: 25,
    course: 'main',
    bulk_prep: false,
    tags: ['quick'],
    blurb: 'Wok, pineapple, plain rice.',
    ingredients: [
      { name: 'Pork Chop', quantity: 150, unit: 'g' },
      { name: 'Pineapple', quantity: 70, unit: 'g' },
      { name: 'Bell Pepper', quantity: 70, unit: 'g' },
      { name: 'Carrot', quantity: 50, unit: 'g' },
      { name: 'White Wine Vinegar', quantity: 15, unit: 'ml' },
      { name: 'Ketchup', quantity: 20, unit: 'g' },
      { name: 'Sugar', quantity: 8, unit: 'g' },
      { name: 'Rice', quantity: 70, unit: 'g' },
    ],
    procedure: [
      'Sear the diced pork, then remove it and stir-fry the vegetables.',
      'Stir vinegar, ketchup and sugar into a sauce and pour in.',
      'Return the pork with the pineapple, bubble 2 minutes, serve with rice.',
    ].join('\n'),
  },
  {
    slug: 'baked-salmon-potatoes-lemon',
    title: 'Baked Salmon with Potatoes and Lemon',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: [],
    blurb: 'Single tray, nothing to think about.',
    ingredients: [
      { name: 'Salmon', quantity: 150, unit: 'g' },
      { name: 'Potato', quantity: 180, unit: 'g' },
      { name: 'Lemon', quantity: 20, unit: 'ml' },
      { name: 'Thyme', quantity: 2, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Roast thinly sliced potatoes in oil at 200 °C for 20 minutes.',
      'Lay the salmon on top with lemon and thyme and give it 12 minutes more.',
    ].join('\n'),
  },
  {
    slug: 'baked-breaded-cod',
    title: 'Baked Breaded Cod with Vegetables',
    minutes: 30,
    course: 'main',
    bulk_prep: false,
    tags: [],
    blurb: 'Crisp without frying; everyone eats it.',
    ingredients: [
      { name: 'Cod', quantity: 160, unit: 'g' },
      { name: 'Breadcrumbs', quantity: 30, unit: 'g' },
      { name: 'Parsley', quantity: 4, unit: 'g' },
      { name: 'Lemon', quantity: 15, unit: 'ml' },
      { name: 'Zucchini', quantity: 100, unit: 'g' },
      { name: 'Cherry Tomato', quantity: 80, unit: 'g' },
      { name: 'Olive Oil', quantity: 15, unit: 'ml' },
    ],
    procedure: [
      'Mix the breadcrumbs with the parsley, lemon zest and oil and press onto the cod.',
      'Sit it on the sliced zucchini and tomatoes in an oiled dish.',
      'Bake at 200 °C for 18 minutes, until the crust is gold and the fish flakes.',
    ].join('\n'),
  },
]

// Format tags double as the modal's sections. One ordered list rather than a
// key array plus a label map, so a group cannot exist in one and be missing
// from the other; `other` collects the recipes carrying no format tag and is
// always last.
export const STARTER_GROUPS = [
  { key: 'pasta', label: 'Pasta' },
  { key: 'soup', label: 'Soups' },
  { key: 'risotto', label: 'Risotto' },
  { key: 'curry', label: 'Curries' },
  { key: 'stew', label: 'Stews and chilis' },
  { key: 'salad', label: 'Salads' },
  { key: 'noodles', label: 'Noodles' },
  { key: 'gnocchi', label: 'Gnocchi' },
  { key: 'rice', label: 'Rice bowls' },
  { key: 'sandwich', label: 'Burgers and wraps' },
  { key: 'other', label: 'Other' },
]

const FORMAT_TAGS = new Set(
  STARTER_GROUPS.map((group) => group.key).filter((key) => key !== 'other'),
)

function starterGroupKey(recipe) {
  return recipe.tags.find((tag) => FORMAT_TAGS.has(tag)) || 'other'
}

// Returns [{ key, label, recipes }] in STARTER_GROUPS order, skipping empty
// groups. One pass over the recipes rather than one filter per group.
export function groupStarterRecipes(recipes) {
  const buckets = new Map(STARTER_GROUPS.map((group) => [group.key, []]))
  recipes.forEach((recipe) => buckets.get(starterGroupKey(recipe)).push(recipe))
  return STARTER_GROUPS.map((group) => ({ ...group, recipes: buckets.get(group.key) })).filter(
    (group) => group.recipes.length > 0,
  )
}
