"""baseline schema from models

Revision ID: 3fc2051c6e3c
Revises: 
Create Date: 2026-08-25 10:08:34.785398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fc2051c6e3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reserved_usernames',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), server_default='system', nullable=False),
    sa.Column('reserved_until', sa.DateTime(), nullable=True),
    sa.CheckConstraint("reason IN ('system', 'released')", name='ck_reserved_username_reason'),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('username_changed_at', sa.DateTime(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('plan_settings', sa.JSON(), nullable=True),
    sa.Column('default_people', sa.Integer(), server_default='2', nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('uq_user_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('season_months', sa.String(), nullable=True),
    sa.Column('unit', sa.Enum('G', 'KG', 'L', 'ML', 'PIECE', name='unit_enum'), nullable=True),
    sa.Column('categories', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_ingredient_user_name')
    )
    op.create_table('meal_plans',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_date')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('bulk_prep', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('date_last_consumed', sa.Date(), nullable=True),
    sa.Column('date_last_rejected', sa.Date(), nullable=True),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('visibility', sa.String(), server_default='private', nullable=False),
    sa.Column('page_layout', sa.JSON(), nullable=True),
    sa.Column('page_theme', sa.JSON(), nullable=True),
    sa.Column('copy_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_recipe_id', sa.Integer(), nullable=True),
    sa.Column('source_user_id', sa.Integer(), nullable=True),
    sa.Column('source_author_username', sa.String(), nullable=True),
    sa.Column('source_recipe_title', sa.String(), nullable=True),
    sa.Column('copied_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("visibility IN ('private', 'unlisted', 'public')", name='ck_recipe_visibility'),
    sa.ForeignKeyConstraint(['source_recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('penalize_repetition', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_user_name')
    )
    op.create_table('meals',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal_number', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('people', sa.Integer(), server_default='2', nullable=False),
    sa.Column('leftover_source_date', sa.Date(), nullable=True),
    sa.Column('leftover_source_meal', sa.Integer(), nullable=True),
    sa.CheckConstraint('(leftover_source_date IS NULL) = (leftover_source_meal IS NULL)', name='ck_meal_leftover_source_all_or_nothing'),
    sa.CheckConstraint('meal_number IN (1,2)', name='meals_meal_number_check'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id', 'plan_date'], ['meal_plans.user_id', 'meal_plans.plan_date'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_date', 'meal_number')
    )
    op.create_table('recipe_favorite_sides',
    sa.Column('main_recipe_id', sa.Integer(), nullable=False),
    sa.Column('side_recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['main_recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['side_recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('main_recipe_id', 'side_recipe_id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Enum('G', 'KG', 'L', 'ML', 'PIECE', name='unit_enum'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.create_table('recipe_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.Column('dismissed_by_recipient_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("mode <> 'person' OR recipient_user_id IS NOT NULL OR recipient_email IS NOT NULL", name='ck_share_person_requires_recipient'),
    sa.CheckConstraint("mode IN ('link', 'person')", name='ck_share_mode'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_shares_created_by_user_id'), 'recipe_shares', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_recipe_shares_recipe_id'), 'recipe_shares', ['recipe_id'], unique=False)
    op.create_index('ix_recipe_shares_recipient_user', 'recipe_shares', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_recipe_shares_token_hash'), 'recipe_shares', ['token_hash'], unique=True)
    op.create_table('recipe_tag',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'tag_id')
    )
    op.create_table('meal_side_dishes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('meal_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('side_recipe_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['side_recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'plan_date', 'meal_number'], ['meals.user_id', 'meals.plan_date', 'meals.meal_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'plan_date', 'meal_number', 'position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_side_dishes')
    op.drop_table('recipe_tag')
    op.drop_index(op.f('ix_recipe_shares_token_hash'), table_name='recipe_shares')
    op.drop_index('ix_recipe_shares_recipient_user', table_name='recipe_shares')
    op.drop_index(op.f('ix_recipe_shares_recipe_id'), table_name='recipe_shares')
    op.drop_index(op.f('ix_recipe_shares_created_by_user_id'), table_name='recipe_shares')
    op.drop_table('recipe_shares')
    op.drop_table('recipe_ingredients')
    op.drop_table('recipe_favorite_sides')
    op.drop_table('meals')
    op.drop_table('tags')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('meal_plans')
    op.drop_table('ingredients')
    op.drop_index('uq_user_username_lower', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('reserved_usernames')
    # ### end Alembic commands ###
