"""alpha invites

ALPHA-GATE: the closed-alpha signup allowlist table. When the alpha ends a
later revision drops it again (see
docs/superpowers/specs/2026-09-30-alpha-allowlist-design.md). No data
migration: the table starts empty, and an empty table means signup is open.

Revision ID: c71bc3b77870
Revises: a60c6f33d41f
Create Date: 2026-09-30 09:51:15.398468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71bc3b77870'
down_revision: Union[str, Sequence[str], None] = 'a60c6f33d41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alpha_invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alpha_invites_email'), 'alpha_invites', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alpha_invites_email'), table_name='alpha_invites')
    op.drop_table('alpha_invites')
    # ### end Alembic commands ###
